"""
PDF Audit Report Generator
===========================
Generates a professional branded PDF report from audit data.
Uses FPDF2 (pure Python, zero system dependencies).
"""

import io
import logging
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF

# Suppress verbose font subsetting logs from fonttools
logging.getLogger("fontTools").setLevel(logging.WARNING)


# ============================================================
# Constants
# ============================================================

FONTS_DIR = Path(__file__).parent / "static" / "fonts"

# Print-safe colors
COLORS = {
    "pass":       (5, 150, 105),     # #059669 emerald
    "warn":       (217, 119, 6),     # #d97706 amber
    "fail":       (220, 38, 38),     # #dc2626 red
    "text":       (26, 26, 26),      # #1a1a1a
    "text_sec":   (77, 77, 77),      # #4d4d4d
    "text_dim":   (125, 125, 125),   # #7d7d7d
    "border":     (220, 225, 230),   # #dce1e6
    "bg":         (244, 246, 248),   # #f4f6f8
    "surface":    (255, 255, 255),
    "record_bg":  (26, 30, 36),      # #1a1e24
    "record_txt": (223, 227, 235),   # #dfe3eb
    "primary":    (10, 61, 107),     # #0a3d6b
    "primary_lt": (26, 92, 148),     # #1a5c94
}

GRADE_COLORS = {
    "A": {"bg": (236, 253, 245), "border": (16, 185, 129), "text": (6, 95, 70)},
    "B": {"bg": (239, 246, 255), "border": (59, 130, 246), "text": (30, 64, 175)},
    "C": {"bg": (255, 251, 235), "border": (245, 158, 11), "text": (146, 64, 14)},
    "D": {"bg": (255, 247, 237), "border": (249, 115, 22), "text": (154, 52, 18)},
    "F": {"bg": (254, 242, 242), "border": (239, 68, 68), "text": (153, 27, 27)},
}


# ============================================================
# HTML tag stripping
# ============================================================

def _strip_html(text: str) -> str:
    """Remove HTML tags and decode entities for PDF rendering."""
    import re
    import html as html_mod
    text = re.sub(r"<br\s*/?>", "\n", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = html_mod.unescape(text)
    return text


# ============================================================
# PDF Report Class
# ============================================================

class AuditPDFReport(FPDF):
    """Professional DNS security audit PDF report."""

    def __init__(self, data: Dict[str, Any]):
        super().__init__()
        self.data = data
        self.domain = data.get("domain", "unknown")
        self.grade = data.get("score", {}).get("grade", "?")
        self.score = data.get("score", {}).get("total", 0)
        self.checks = data.get("checks", [])
        self.priority_fixes = data.get("priority_fixes", [])
        self.vendors = data.get("vendors", [])
        self.anomalies = data.get("anomalies") or []
        self.remediation_plan = data.get("remediation_plan") or {}
        self.resilience = data.get("resilience") or {}
        self.score_data = data.get("score", {})
        self._records_for_appendix = []

        # Register fonts
        self._register_fonts()

        # Page setup
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 15, 20)

    def _register_fonts(self):
        """Register bundled fonts, fallback to Helvetica."""
        dm_regular = FONTS_DIR / "DMSans-Regular.ttf"
        dm_bold = FONTS_DIR / "DMSans-Bold.ttf"
        jb_mono = FONTS_DIR / "JetBrainsMono-Regular.ttf"

        if dm_regular.exists():
            self.add_font("DMSans", "", str(dm_regular), uni=True)
        if dm_bold.exists():
            self.add_font("DMSans", "B", str(dm_bold), uni=True)
        if jb_mono.exists():
            self.add_font("JBMono", "", str(jb_mono), uni=True)

        # Set defaults
        self._font_body = "DMSans" if dm_regular.exists() else "Helvetica"
        self._font_mono = "JBMono" if jb_mono.exists() else "Courier"

    def header(self):
        """Page header with thin branded bar."""
        # Skip header on page 1 (has its own branding)
        if self.page_no() == 1:
            return
        self.set_fill_color(*COLORS["primary"])
        self.rect(0, 0, 210, 3, "F")
        self.set_y(8)
        self.set_font(self._font_body, "B", 8)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 5, f"DNS Security Audit | {self.domain}", align="L")
        self.ln(10)

    def footer(self):
        """Page footer with branding and page number."""
        self.set_y(-15)
        self.set_font(self._font_body, "", 7)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 5, f"Generated by dns-audit.com  |  Page {self.page_no()} of {{nb}}", align="C")

    # ============================================================
    # Page 1: Executive Summary
    # ============================================================

    def _render_executive_summary(self):
        """Render the executive summary page."""
        self.add_page()

        # Top accent bar
        self.set_fill_color(*COLORS["primary"])
        self.rect(0, 0, 210, 4, "F")

        # Logo area
        self.set_y(14)
        self.set_font(self._font_body, "B", 22)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 10, "DNS Security Audit Report", align="C", new_x="LMARGIN", new_y="NEXT")

        # Branding
        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 5, "dns-audit.com", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)

        # Domain name
        self.set_font(self._font_body, "B", 18)
        self.set_text_color(*COLORS["text"])
        self.cell(0, 10, self.domain, align="C", new_x="LMARGIN", new_y="NEXT")

        # Timestamp
        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_dim"])
        ts = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
        self.cell(0, 5, f"Audited: {ts}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

        # Grade circle
        self._render_grade_circle()
        self.ln(8)

        # Summary stats bar
        self._render_summary_bar()
        self.ln(10)

        # Risk level
        self._render_risk_level()
        self.ln(6)

        # Category score breakdown
        self._render_category_breakdown()
        self.ln(6)

        # Priority fixes
        if self.priority_fixes:
            self._render_priority_fixes()
            self.ln(6)

        # Vendors
        if self.vendors:
            self._render_vendors()

    def _render_grade_circle(self):
        """Draw a large grade indicator."""
        gc = GRADE_COLORS.get(self.grade, GRADE_COLORS.get("F"))
        cx = 105  # center of page
        cy = self.get_y() + 22
        r = 20

        # Background circle
        self.set_fill_color(*gc["bg"])
        self.set_draw_color(*gc["border"])
        self.set_line_width(1.5)
        self.circle(cx, cy, r, style="FD")

        # Grade letter
        self.set_font(self._font_body, "B", 32)
        self.set_text_color(*gc["text"])
        self.set_y(cy - 10)
        self.cell(0, 16, self.grade, align="C", new_x="LMARGIN", new_y="NEXT")

        # Score below
        self.set_font(self._font_body, "", 10)
        self.set_text_color(*gc["text"])
        self.cell(0, 6, f"{round(self.score)} / 100", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_y(cy + r + 4)

    def _render_summary_bar(self):
        """Render pass/warn/fail summary as colored boxes in a row."""
        pass_count = sum(1 for c in self.checks if c.get("status") == "pass")
        warn_count = sum(1 for c in self.checks if c.get("status") == "warn")
        fail_count = sum(1 for c in self.checks if c.get("status") == "fail")

        box_w = 50
        gap = 5
        total_w = box_w * 3 + gap * 2
        start_x = (210 - total_w) / 2
        row_y = self.get_y()  # fixed y for entire row

        for i, (label, count, color) in enumerate([
            ("Passing", pass_count, COLORS["pass"]),
            ("Warnings", warn_count, COLORS["warn"]),
            ("Issues", fail_count, COLORS["fail"]),
        ]):
            x = start_x + i * (box_w + gap)

            # Box background
            self.set_fill_color(color[0], color[1], color[2])
            self.rect(x, row_y, box_w, 22, "F")

            # Count
            self.set_font(self._font_body, "B", 16)
            self.set_text_color(255, 255, 255)
            self.set_xy(x, row_y + 2)
            self.cell(box_w, 10, str(count), align="C")

            # Label
            self.set_font(self._font_body, "", 7)
            self.set_xy(x, row_y + 12)
            self.cell(box_w, 6, label.upper(), align="C")

        self.set_y(row_y + 26)

    def _render_priority_fixes(self):
        """Render priority fixes section."""
        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["fail"])
        self.cell(0, 7, "Priority Fixes", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for i, fix in enumerate(self.priority_fixes, 1):
            self.set_font(self._font_body, "B", 9)
            self.set_text_color(*COLORS["fail"])
            num_w = 6
            self.cell(num_w, 5, f"{i}.")

            self.set_font(self._font_body, "", 9)
            self.set_text_color(*COLORS["text"])
            self.multi_cell(0, 5, _strip_html(fix), new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

    def _render_vendors(self):
        """Render detected email services."""
        self.set_font(self._font_body, "B", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 6, "DETECTED EMAIL SERVICES", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        vendor_parts = []
        for v in self.vendors:
            name = v.get("name", "Unknown")
            vendor_parts.append(name)

        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_sec"])
        self.multi_cell(0, 5, " · ".join(vendor_parts), new_x="LMARGIN", new_y="NEXT")

    def _render_risk_level(self):
        """Render risk level badge based on grade."""
        risk_map = {
            "A": ("Low", COLORS["pass"]),
            "B": ("Low", COLORS["pass"]),
            "C": ("Medium", COLORS["warn"]),
            "D": ("High", COLORS["fail"]),
            "F": ("Critical", COLORS["fail"]),
        }
        risk_label, risk_color = risk_map.get(self.grade, ("Unknown", COLORS["text_dim"]))

        self.set_font(self._font_body, "B", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 6, "RISK LEVEL", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font(self._font_body, "B", 12)
        self.set_text_color(*risk_color)
        self.cell(0, 7, risk_label, align="C", new_x="LMARGIN", new_y="NEXT")

    def _render_category_breakdown(self):
        """Render category score bars."""
        category_scores = self.score_data.get("category_scores") or {}
        if not category_scores:
            return

        weights = {
            "dmarc": 30, "spf": 25, "dkim": 20,
            "best_practices": 10, "key_security": 10, "vendor_intelligence": 5,
        }
        labels = {
            "dmarc": "DMARC", "spf": "SPF", "dkim": "DKIM",
            "best_practices": "Best Practices", "key_security": "Key Security",
            "vendor_intelligence": "Vendor Intel",
        }

        self.set_font(self._font_body, "B", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 6, "SCORE BREAKDOWN", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        x = self.l_margin
        bar_w = 100
        label_w = 45
        score_w = 25

        for cat_key in ["dmarc", "spf", "dkim", "best_practices", "key_security", "vendor_intelligence"]:
            cat_score = category_scores.get(cat_key, 0)
            max_score = weights.get(cat_key, 10)
            label = labels.get(cat_key, cat_key)
            pct = min(cat_score / max_score, 1.0) if max_score > 0 else 0

            # Label
            self.set_font(self._font_body, "", 8)
            self.set_text_color(*COLORS["text_sec"])
            self.set_x(x)
            self.cell(label_w, 5, label)

            # Bar background
            bar_y = self.get_y() + 0.5
            self.set_fill_color(*COLORS["bg"])
            self.rect(x + label_w, bar_y, bar_w, 4, "F")

            # Bar fill
            fill_color = COLORS["pass"] if pct >= 0.7 else COLORS["warn"] if pct >= 0.4 else COLORS["fail"]
            self.set_fill_color(*fill_color)
            if pct > 0:
                self.rect(x + label_w, bar_y, bar_w * pct, 4, "F")

            # Score text
            self.set_font(self._font_body, "", 7)
            self.set_text_color(*COLORS["text_dim"])
            self.set_xy(x + label_w + bar_w + 3, self.get_y())
            self.cell(score_w, 5, f"{cat_score:.0f}/{max_score}")

            self.ln(6)

    # ============================================================
    # Authentication Resilience
    # ============================================================

    def _render_resilience(self):
        """Render the authentication resilience section."""
        if not self.resilience:
            return

        level = self.resilience.get("level", "")
        summary = self.resilience.get("summary", "")
        risk = self.resilience.get("risk", "")
        mechanisms = self.resilience.get("mechanisms", {})

        if not summary:
            return

        if self.get_y() > 240:
            self.add_page()

        # Header
        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 7, "Authentication Resilience", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        # Level badge + summary
        level_colors = {
            "high": COLORS["pass"],
            "moderate": COLORS["warn"],
            "low": COLORS["fail"],
            "none": COLORS["fail"],
        }
        level_color = level_colors.get(level, COLORS["text_dim"])

        self.set_font(self._font_body, "B", 9)
        self.set_text_color(*level_color)
        self.cell(20, 5, level.upper())
        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text"])
        self.multi_cell(0, 5, summary, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        # Mechanisms
        x = self.l_margin
        for name, info in mechanisms.items():
            status = info.get("status", "")
            note = info.get("note", "")
            self.set_font(self._font_mono, "", 8)
            self.set_text_color(*COLORS["text"])
            self.set_x(x)
            self.cell(15, 4.5, name.upper())
            self.set_font(self._font_body, "B", 8)
            s_color = COLORS["pass"] if status in ("pass", "detected", "reject", "quarantine") else COLORS["warn"] if status in ("not_detected", "none") else COLORS["fail"]
            self.set_text_color(*s_color)
            self.cell(25, 4.5, status)
            if note:
                self.set_font(self._font_body, "", 7)
                self.set_text_color(*COLORS["text_dim"])
                self.cell(0, 4.5, note[:80], new_x="LMARGIN", new_y="NEXT")
            else:
                self.ln(4.5)

        # Risk text
        if risk:
            self.ln(2)
            self.set_font(self._font_body, "", 8)
            self.set_text_color(*COLORS["text_sec"])
            self.set_x(x)
            self.multi_cell(170, 4.5, risk, new_x="LMARGIN", new_y="NEXT")

        self.ln(4)

    # ============================================================
    # Anomalies Section
    # ============================================================

    def _render_anomalies(self):
        """Render the 'What's Unusual' anomaly section."""
        if not self.anomalies:
            return

        if self.get_y() > 240:
            self.add_page()

        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 7, "What's Unusual", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        severity_colors = {
            "critical": COLORS["fail"],
            "high": COLORS["warn"],
            "medium": COLORS["text_dim"],
        }

        for anomaly in self.anomalies:
            if self.get_y() > 265:
                self.add_page()

            sev = anomaly.get("severity", "medium")
            sev_color = severity_colors.get(sev, COLORS["text_dim"])
            x = self.l_margin
            w = 210 - self.l_margin - self.r_margin

            # Severity accent
            self.set_fill_color(*sev_color)
            self.rect(x, self.get_y(), 2.5, 12, "F")

            # Title
            self.set_font(self._font_body, "B", 8.5)
            self.set_text_color(*sev_color)
            sev_label = {"critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM"}.get(sev, sev.upper())
            self.set_x(x + 5)
            self.cell(18, 5, sev_label)

            self.set_font(self._font_body, "B", 8.5)
            self.set_text_color(*COLORS["text"])
            self.cell(0, 5, anomaly.get("title", ""), new_x="LMARGIN", new_y="NEXT")

            # Description
            desc = anomaly.get("description", "")
            if desc:
                self.set_font(self._font_body, "", 8)
                self.set_text_color(*COLORS["text_sec"])
                self.set_x(x + 5)
                self.multi_cell(w - 5, 4, desc, new_x="LMARGIN", new_y="NEXT")

            # Recommendation
            rec = anomaly.get("recommendation", "")
            if rec:
                self.set_font(self._font_body, "", 7.5)
                self.set_text_color(*COLORS["pass"])
                self.set_x(x + 5)
                self.multi_cell(w - 5, 4, f"-> {rec}", new_x="LMARGIN", new_y="NEXT")

            self.ln(3)

    # ============================================================
    # Remediation Plan
    # ============================================================

    def _render_remediation_plan(self):
        """Render the remediation plan section."""
        immediate = self.remediation_plan.get("immediate") or []
        short_term = self.remediation_plan.get("short_term") or []
        long_term = self.remediation_plan.get("long_term") or []

        if not immediate and not short_term and not long_term:
            return

        self.add_page()

        self.set_font(self._font_body, "B", 14)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 8, "Remediation Plan", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

        phases = [
            ("Immediate Actions", immediate, COLORS["fail"]),
            ("Short-Term (1-2 Weeks)", short_term, COLORS["warn"]),
            ("Long-Term (1-3 Months)", long_term, COLORS["text_dim"]),
        ]

        for phase_title, steps, phase_color in phases:
            if not steps:
                continue

            if self.get_y() > 255:
                self.add_page()

            # Phase header
            self.set_font(self._font_body, "B", 10)
            self.set_text_color(*phase_color)
            self.cell(0, 7, phase_title, new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

            x = self.l_margin
            w = 210 - self.l_margin - self.r_margin

            for i, step in enumerate(steps, 1):
                if self.get_y() > 268:
                    self.add_page()

                # Step number + title
                self.set_font(self._font_body, "B", 9)
                self.set_text_color(*COLORS["text"])
                self.set_x(x)
                self.cell(8, 5, f"{i}.")

                self.set_font(self._font_body, "B", 9)
                self.cell(0, 5, step.get("title", ""), new_x="LMARGIN", new_y="NEXT")

                # Description
                desc = step.get("description", "")
                if desc:
                    self.set_font(self._font_body, "", 8)
                    self.set_text_color(*COLORS["text_sec"])
                    self.set_x(x + 8)
                    self.multi_cell(w - 8, 4.2, desc, new_x="LMARGIN", new_y="NEXT")

                # Effort + impact badges
                effort = step.get("effort", "")
                impact = step.get("impact", "")
                if effort or impact:
                    self.set_font(self._font_body, "", 7)
                    self.set_text_color(*COLORS["text_dim"])
                    self.set_x(x + 8)
                    badge_text = []
                    if effort:
                        badge_text.append(f"Effort: {effort}")
                    if impact:
                        badge_text.append(f"Impact: {impact}")
                    self.cell(0, 4, " | ".join(badge_text), new_x="LMARGIN", new_y="NEXT")

                self.ln(3)

            self.ln(3)

    # ============================================================
    # Appendix -- Raw DNS Records
    # ============================================================

    def _render_appendix(self):
        """Render appendix with raw DNS records."""
        if not self._records_for_appendix:
            return

        self.add_page()

        self.set_font(self._font_body, "B", 14)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 8, "Appendix: Raw DNS Records", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

        x = self.l_margin
        w = 210 - self.l_margin - self.r_margin

        for entry in self._records_for_appendix:
            if self.get_y() > 250:
                self.add_page()

            # Check name
            self.set_font(self._font_body, "B", 9)
            self.set_text_color(*COLORS["text"])
            self.cell(0, 5, entry["name"], new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

            # Record block
            self._render_record_block(entry["record"], x, w)

    # ============================================================
    # Pages 2+: Detailed Findings
    # ============================================================

    def _render_check_cards(self):
        """Render each check as a card block."""
        self.add_page()  # Start checks on a fresh page

        # Section heading
        self.set_font(self._font_body, "B", 14)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 8, "Findings", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

        for check in self.checks:
            self._render_check_card(check)

    def _estimate_card_height(self, check: Dict) -> float:
        """Estimate the height a card will occupy (approximate).
        Records are now in the appendix, so not counted here."""
        h = 14  # header
        if check.get("explanation"):
            text = _strip_html(check["explanation"])
            chars_per_line = 85
            h += max(1, math.ceil(len(text) / chars_per_line)) * 5 + 4
        details = check.get("details", [])
        h += len(details) * 5.5
        return h

    def _render_check_card(self, check: Dict):
        """Render a single check card."""
        estimated_h = self._estimate_card_height(check)

        # Page break if card won't fit
        if self.get_y() + estimated_h > 275:
            self.add_page()

        start_y = self.get_y()
        x = self.l_margin
        w = 210 - self.l_margin - self.r_margin

        # Card background
        self.set_fill_color(*COLORS["surface"])
        self.set_draw_color(*COLORS["border"])
        self.set_line_width(0.3)

        # Status color for left accent
        status = check.get("status", "pass")
        status_color = COLORS.get(status, COLORS["pass"])

        # Card header
        self.set_fill_color(*status_color)
        self.rect(x, start_y, 3, 12, "F")

        self.set_xy(x + 6, start_y + 1)
        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["text"])
        name = check.get("name", "")
        self.cell(80, 6, name)

        # Status pill
        pill_label = check.get("pill_label") or {"pass": "Pass", "warn": "Warning", "fail": "Issue"}.get(status, "")
        pill_color = status_color
        self.set_font(self._font_body, "B", 7)
        pill_w = self.get_string_width(pill_label) + 6
        self.set_xy(x + 6 + 82, start_y + 2)
        self.set_fill_color(*pill_color)
        self.set_text_color(255, 255, 255)
        self.cell(pill_w, 5, pill_label, fill=True, align="C")

        # Verdict
        verdict = check.get("verdict", "")
        if verdict:
            self.set_font(self._font_body, "", 8)
            self.set_text_color(*COLORS["text_dim"])
            self.set_xy(x + 6 + 82 + pill_w + 3, start_y + 2)
            # Truncate if too long
            max_verdict_w = w - 90 - pill_w - 6
            if self.get_string_width(verdict) > max_verdict_w:
                while self.get_string_width(verdict + "...") > max_verdict_w and len(verdict) > 5:
                    verdict = verdict[:-1]
                verdict += "..."
            self.cell(0, 5, verdict)

        self.set_y(start_y + 14)

        # DNS record -- collect for appendix instead of inline
        if check.get("record"):
            self._records_for_appendix.append({
                "name": check.get("name", ""),
                "record": check["record"],
            })

        # Explanation
        if check.get("explanation"):
            self.set_font(self._font_body, "", 8.5)
            self.set_text_color(*COLORS["text_sec"])
            text = _strip_html(check["explanation"])
            self.set_x(x)
            self.multi_cell(w, 4.5, text, new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

        # Detail items
        for detail in check.get("details", []):
            self._render_detail_item(detail, x, w)

        self.ln(3)

        # Bottom border
        self.set_draw_color(*COLORS["border"])
        self.set_line_width(0.2)
        self.line(x, self.get_y(), x + w, self.get_y())
        self.ln(4)

    def _render_record_block(self, record: str, x: float, w: float):
        """Render a DNS record in a dark terminal-style block."""
        self.set_font(self._font_mono, "", 7)
        content_w = w - 8

        # Calculate wrapped height
        lines = record.split("\n")
        total_lines = 0
        for line in lines:
            line_w = self.get_string_width(line)
            total_lines += max(1, math.ceil(line_w / content_w)) if line else 1
        block_h = total_lines * 4.2 + 6

        # Page break if needed
        if self.get_y() + block_h > 275:
            self.add_page()

        y = self.get_y()
        self.set_fill_color(*COLORS["record_bg"])
        self.rect(x, y, w, block_h, "F")

        self.set_text_color(*COLORS["record_txt"])
        self.set_xy(x + 4, y + 3)
        self.multi_cell(content_w, 4.2, record, align="L")

        self.set_y(y + block_h + 3)

    def _render_detail_item(self, detail: Dict, x: float, w: float):
        """Render a single detail item with severity icon."""
        dtype = detail.get("type", "info")
        text = detail.get("text", "")

        icon_map = {
            "error": ("X", COLORS["fail"]),
            "warning": ("!", COLORS["warn"]),
            "good": ("+", COLORS["pass"]),
            "info": ("-", COLORS["text_dim"]),
        }
        icon, color = icon_map.get(dtype, ("·", COLORS["text_dim"]))

        self.set_font(self._font_body, "B", 8)
        self.set_text_color(*color)
        self.set_x(x + 2)
        self.cell(5, 4.5, icon)

        self.set_font(self._font_body, "", 8)
        self.set_text_color(*color)
        self.multi_cell(w - 10, 4.5, text, new_x="LMARGIN", new_y="NEXT")

    # ============================================================
    # Build
    # ============================================================

    def build(self) -> bytes:
        """Generate the complete PDF and return as bytes."""
        self.alias_nb_pages()

        # Page 1: Executive Summary (enhanced with risk level + category breakdown)
        self._render_executive_summary()

        # Authentication Resilience
        self._render_resilience()

        # Anomalies -- "What's Unusual" (if any)
        self._render_anomalies()

        # Remediation Plan (if any steps)
        self._render_remediation_plan()

        # Detailed Findings (records moved to appendix)
        self._render_check_cards()

        # Appendix -- Raw DNS Records
        self._render_appendix()

        return self.output()


# ============================================================
# Public API
# ============================================================

def generate_audit_pdf(data: Dict[str, Any]) -> bytes:
    """Generate a professional PDF audit report from audit data."""
    report = AuditPDFReport(data)
    return report.build()
