"""
PDF Audit Report Generator
===========================
Generates a professional branded PDF report from audit data.
Uses FPDF2 (pure Python, zero system dependencies).
"""

import io
import logging
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF

# Suppress verbose font subsetting logs from fonttools
logging.getLogger("fontTools").setLevel(logging.WARNING)


# ============================================================
# Constants
# ============================================================

FONTS_DIR = Path(__file__).parent / "static" / "fonts"

# Print-safe colors
COLORS = {
    "pass":       (5, 150, 105),     # #059669 emerald
    "warn":       (217, 119, 6),     # #d97706 amber
    "fail":       (220, 38, 38),     # #dc2626 red
    "text":       (26, 26, 26),      # #1a1a1a
    "text_sec":   (77, 77, 77),      # #4d4d4d
    "text_dim":   (125, 125, 125),   # #7d7d7d
    "border":     (220, 225, 230),   # #dce1e6
    "bg":         (244, 246, 248),   # #f4f6f8
    "surface":    (255, 255, 255),
    "record_bg":  (26, 30, 36),      # #1a1e24
    "record_txt": (223, 227, 235),   # #dfe3eb
    "primary":    (10, 61, 107),     # #0a3d6b
    "primary_lt": (26, 92, 148),     # #1a5c94
}

GRADE_COLORS = {
    "A": {"bg": (236, 253, 245), "border": (16, 185, 129), "text": (6, 95, 70)},
    "B": {"bg": (239, 246, 255), "border": (59, 130, 246), "text": (30, 64, 175)},
    "C": {"bg": (255, 251, 235), "border": (245, 158, 11), "text": (146, 64, 14)},
    "D": {"bg": (255, 247, 237), "border": (249, 115, 22), "text": (154, 52, 18)},
    "F": {"bg": (254, 242, 242), "border": (239, 68, 68), "text": (153, 27, 27)},
}


# ============================================================
# HTML tag stripping
# ============================================================

def _strip_html(text: str) -> str:
    """Remove HTML tags and decode entities for PDF rendering."""
    import re
    import html as html_mod
    text = re.sub(r"<br\s*/?>", "\n", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = html_mod.unescape(text)
    return text


# ============================================================
# PDF Report Class
# ============================================================

class AuditPDFReport(FPDF):
    """Professional DNS security audit PDF report."""

    def __init__(self, data: Dict[str, Any]):
        super().__init__()
        self.data = data
        self.domain = data.get("domain", "unknown")
        self.grade = data.get("score", {}).get("grade", "?")
        self.score = data.get("score", {}).get("total", 0)
        self.checks = data.get("checks", [])
        self.priority_fixes = data.get("priority_fixes", [])
        self.vendors = data.get("vendors", [])

        # Register fonts
        self._register_fonts()

        # Page setup
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 15, 20)

    def _register_fonts(self):
        """Register bundled fonts, fallback to Helvetica."""
        dm_regular = FONTS_DIR / "DMSans-Regular.ttf"
        dm_bold = FONTS_DIR / "DMSans-Bold.ttf"
        jb_mono = FONTS_DIR / "JetBrainsMono-Regular.ttf"

        if dm_regular.exists():
            self.add_font("DMSans", "", str(dm_regular), uni=True)
        if dm_bold.exists():
            self.add_font("DMSans", "B", str(dm_bold), uni=True)
        if jb_mono.exists():
            self.add_font("JBMono", "", str(jb_mono), uni=True)

        # Set defaults
        self._font_body = "DMSans" if dm_regular.exists() else "Helvetica"
        self._font_mono = "JBMono" if jb_mono.exists() else "Courier"

    def header(self):
        """Page header with thin branded bar."""
        # Skip header on page 1 (has its own branding)
        if self.page_no() == 1:
            return
        self.set_fill_color(*COLORS["primary"])
        self.rect(0, 0, 210, 3, "F")
        self.set_y(8)
        self.set_font(self._font_body, "B", 8)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 5, f"DNS Security Audit | {self.domain}", align="L")
        self.ln(10)

    def footer(self):
        """Page footer with branding and page number."""
        self.set_y(-15)
        self.set_font(self._font_body, "", 7)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 5, f"Generated by dns-audit.com  |  Page {self.page_no()} of {{nb}}", align="C")

    # ============================================================
    # Page 1: Executive Summary
    # ============================================================

    def _render_executive_summary(self):
        """Render the executive summary page."""
        self.add_page()

        # Top accent bar
        self.set_fill_color(*COLORS["primary"])
        self.rect(0, 0, 210, 4, "F")

        # Logo area
        self.set_y(14)
        self.set_font(self._font_body, "B", 22)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 10, "DNS Security Audit Report", align="C", new_x="LMARGIN", new_y="NEXT")

        # Branding
        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 5, "dns-audit.com", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)

        # Domain name
        self.set_font(self._font_body, "B", 18)
        self.set_text_color(*COLORS["text"])
        self.cell(0, 10, self.domain, align="C", new_x="LMARGIN", new_y="NEXT")

        # Timestamp
        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_dim"])
        ts = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
        self.cell(0, 5, f"Audited: {ts}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

        # Grade circle
        self._render_grade_circle()
        self.ln(8)

        # Summary stats bar
        self._render_summary_bar()
        self.ln(10)

        # Priority fixes
        if self.priority_fixes:
            self._render_priority_fixes()
            self.ln(6)

        # Vendors
        if self.vendors:
            self._render_vendors()

    def _render_grade_circle(self):
        """Draw a large grade indicator."""
        gc = GRADE_COLORS.get(self.grade, GRADE_COLORS.get("F"))
        cx = 105  # center of page
        cy = self.get_y() + 22
        r = 20

        # Background circle
        self.set_fill_color(*gc["bg"])
        self.set_draw_color(*gc["border"])
        self.set_line_width(1.5)
        self.circle(cx, cy, r, style="FD")

        # Grade letter
        self.set_font(self._font_body, "B", 32)
        self.set_text_color(*gc["text"])
        self.set_y(cy - 10)
        self.cell(0, 16, self.grade, align="C", new_x="LMARGIN", new_y="NEXT")

        # Score below
        self.set_font(self._font_body, "", 10)
        self.set_text_color(*gc["text"])
        self.cell(0, 6, f"{round(self.score)} / 100", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_y(cy + r + 4)

    def _render_summary_bar(self):
        """Render pass/warn/fail summary as colored boxes in a row."""
        pass_count = sum(1 for c in self.checks if c.get("status") == "pass")
        warn_count = sum(1 for c in self.checks if c.get("status") == "warn")
        fail_count = sum(1 for c in self.checks if c.get("status") == "fail")

        box_w = 50
        gap = 5
        total_w = box_w * 3 + gap * 2
        start_x = (210 - total_w) / 2
        row_y = self.get_y()  # fixed y for entire row

        for i, (label, count, color) in enumerate([
            ("Passing", pass_count, COLORS["pass"]),
            ("Warnings", warn_count, COLORS["warn"]),
            ("Issues", fail_count, COLORS["fail"]),
        ]):
            x = start_x + i * (box_w + gap)

            # Box background
            self.set_fill_color(color[0], color[1], color[2])
            self.rect(x, row_y, box_w, 22, "F")

            # Count
            self.set_font(self._font_body, "B", 16)
            self.set_text_color(255, 255, 255)
            self.set_xy(x, row_y + 2)
            self.cell(box_w, 10, str(count), align="C")

            # Label
            self.set_font(self._font_body, "", 7)
            self.set_xy(x, row_y + 12)
            self.cell(box_w, 6, label.upper(), align="C")

        self.set_y(row_y + 26)

    def _render_priority_fixes(self):
        """Render priority fixes section."""
        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["fail"])
        self.cell(0, 7, "Priority Fixes", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for i, fix in enumerate(self.priority_fixes, 1):
            self.set_font(self._font_body, "B", 9)
            self.set_text_color(*COLORS["fail"])
            num_w = 6
            self.cell(num_w, 5, f"{i}.")

            self.set_font(self._font_body, "", 9)
            self.set_text_color(*COLORS["text"])
            self.multi_cell(0, 5, _strip_html(fix), new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

    def _render_vendors(self):
        """Render detected email services."""
        self.set_font(self._font_body, "B", 9)
        self.set_text_color(*COLORS["text_dim"])
        self.cell(0, 6, "DETECTED EMAIL SERVICES", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        vendor_parts = []
        for v in self.vendors:
            name = v.get("name", "Unknown")
            conf = v.get("confidence", 0)
            vendor_parts.append(f"{name} ({conf}%)")

        self.set_font(self._font_body, "", 9)
        self.set_text_color(*COLORS["text_sec"])
        self.multi_cell(0, 5, " · ".join(vendor_parts), new_x="LMARGIN", new_y="NEXT")

    # ============================================================
    # Pages 2+: Detailed Check Cards
    # ============================================================

    def _render_check_cards(self):
        """Render each check as a card block."""
        self.add_page()  # Start checks on a fresh page
        for check in self.checks:
            self._render_check_card(check)

    def _estimate_card_height(self, check: Dict) -> float:
        """Estimate the height a card will occupy (approximate)."""
        h = 14  # header
        if check.get("record"):
            lines = len(check["record"].split("\n"))
            h += 6 + lines * 4.5
        if check.get("explanation"):
            text = _strip_html(check["explanation"])
            chars_per_line = 85
            h += max(1, math.ceil(len(text) / chars_per_line)) * 5 + 4
        details = check.get("details", [])
        h += len(details) * 5.5
        return h

    def _render_check_card(self, check: Dict):
        """Render a single check card."""
        estimated_h = self._estimate_card_height(check)

        # Page break if card won't fit
        if self.get_y() + estimated_h > 275:
            self.add_page()

        start_y = self.get_y()
        x = self.l_margin
        w = 210 - self.l_margin - self.r_margin

        # Card background
        self.set_fill_color(*COLORS["surface"])
        self.set_draw_color(*COLORS["border"])
        self.set_line_width(0.3)

        # Status color for left accent
        status = check.get("status", "pass")
        status_color = COLORS.get(status, COLORS["pass"])

        # Card header
        self.set_fill_color(*status_color)
        self.rect(x, start_y, 3, 12, "F")

        self.set_xy(x + 6, start_y + 1)
        self.set_font(self._font_body, "B", 11)
        self.set_text_color(*COLORS["text"])
        name = check.get("name", "")
        self.cell(80, 6, name)

        # Status pill
        pill_label = check.get("pill_label") or {"pass": "Pass", "warn": "Warning", "fail": "Issue"}.get(status, "")
        pill_color = status_color
        self.set_font(self._font_body, "B", 7)
        pill_w = self.get_string_width(pill_label) + 6
        self.set_xy(x + 6 + 82, start_y + 2)
        self.set_fill_color(*pill_color)
        self.set_text_color(255, 255, 255)
        self.cell(pill_w, 5, pill_label, fill=True, align="C")

        # Verdict
        verdict = check.get("verdict", "")
        if verdict:
            self.set_font(self._font_body, "", 8)
            self.set_text_color(*COLORS["text_dim"])
            self.set_xy(x + 6 + 82 + pill_w + 3, start_y + 2)
            # Truncate if too long
            max_verdict_w = w - 90 - pill_w - 6
            if self.get_string_width(verdict) > max_verdict_w:
                while self.get_string_width(verdict + "...") > max_verdict_w and len(verdict) > 5:
                    verdict = verdict[:-1]
                verdict += "..."
            self.cell(0, 5, verdict)

        self.set_y(start_y + 14)

        # DNS record
        if check.get("record"):
            self._render_record_block(check["record"], x, w)

        # Explanation
        if check.get("explanation"):
            self.set_font(self._font_body, "", 8.5)
            self.set_text_color(*COLORS["text_sec"])
            text = _strip_html(check["explanation"])
            self.set_x(x)
            self.multi_cell(w, 4.5, text, new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

        # Detail items
        for detail in check.get("details", []):
            self._render_detail_item(detail, x, w)

        self.ln(3)

        # Bottom border
        self.set_draw_color(*COLORS["border"])
        self.set_line_width(0.2)
        self.line(x, self.get_y(), x + w, self.get_y())
        self.ln(4)

    def _render_record_block(self, record: str, x: float, w: float):
        """Render a DNS record in a dark terminal-style block."""
        self.set_font(self._font_mono, "", 7)
        content_w = w - 8

        # Calculate wrapped height
        lines = record.split("\n")
        total_lines = 0
        for line in lines:
            line_w = self.get_string_width(line)
            total_lines += max(1, math.ceil(line_w / content_w)) if line else 1
        block_h = total_lines * 4.2 + 6

        # Page break if needed
        if self.get_y() + block_h > 275:
            self.add_page()

        y = self.get_y()
        self.set_fill_color(*COLORS["record_bg"])
        self.rect(x, y, w, block_h, "F")

        self.set_text_color(*COLORS["record_txt"])
        self.set_xy(x + 4, y + 3)
        self.multi_cell(content_w, 4.2, record, align="L")

        self.set_y(y + block_h + 3)

    def _render_detail_item(self, detail: Dict, x: float, w: float):
        """Render a single detail item with severity icon."""
        dtype = detail.get("type", "info")
        text = detail.get("text", "")

        icon_map = {
            "error": ("X", COLORS["fail"]),
            "warning": ("!", COLORS["warn"]),
            "good": ("+", COLORS["pass"]),
            "info": ("-", COLORS["text_dim"]),
        }
        icon, color = icon_map.get(dtype, ("·", COLORS["text_dim"]))

        self.set_font(self._font_body, "B", 8)
        self.set_text_color(*color)
        self.set_x(x + 2)
        self.cell(5, 4.5, icon)

        self.set_font(self._font_body, "", 8)
        self.set_text_color(*color)
        self.multi_cell(w - 10, 4.5, text, new_x="LMARGIN", new_y="NEXT")

    # ============================================================
    # Build
    # ============================================================

    def build(self) -> bytes:
        """Generate the complete PDF and return as bytes."""
        self.alias_nb_pages()

        # Page 1: Executive Summary
        self._render_executive_summary()

        # Pages 2+: Detailed Check Cards
        self._render_check_cards()

        return self.output()


# ============================================================
# Public API
# ============================================================

def generate_audit_pdf(data: Dict[str, Any]) -> bytes:
    """Generate a professional PDF audit report from audit data."""
    report = AuditPDFReport(data)
    return report.build()
